language: go

go:
    - 1.7.x
    - 1.8.x
    - 1.9.x

install:
    - make deps
    - glide install

script:
    - make build-ci

deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file:
        - bin/sharelatex2git-linux
        - bin/sharelatex2git-darwin
    skip_cleanup: true
    on:
        tags: true
