language: go

go:
    - 1.11.x
    - 1.12.x
    - 1.13.x
    - master

env:
    - GO111MODULE=on

install:
    - go mod download

script:
    - make build-ci

deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file:
        - bin/overleaf2git-linux
        - bin/overleaf2git-darwin
    skip_cleanup: true
    on:
        tags: true
        condition: $TRAVIS_GO_VERSION =~ ^1\.13\..+$
